---
- name: Install Jenkins on Various Platforms
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: "install_type"
      prompt: "How would you like to install Jenkins? (docker/linux)"
      private: no
    - name: "mount_path"
      prompt: "Enter the mount path to use in the Docker container for Jenkins"
      when: install_type == "docker"
      private: no

  tasks:
    - name: Ensure Jenkins group exists
      ansible.builtin.group:
        name: jenkins
        state: present

    - name: Ensure Jenkins user exists with /bin/false shell
      ansible.builtin.user:
        name: jenkins
        group: jenkins
        shell: /bin/false
        state: present
        create_home: yes
      when: install_type != "docker"

    - name: Install Docker for Debian/Ubuntu
      import_tasks: docker-playbooks/debian-ubuntu.yml
      when: ansible_facts['os_family'] == "Debian" and install_type == "docker"

    - name: Install Docker for Fedora
      import_tasks: docker-playbooks/fedora.yml
      when: ansible_facts['os_family'] == "Fedora" and install_type == "docker"

    - name: Install Docker for Red Hat/Alma/Rocky
      import_tasks: docker-playbooks/redhat.yml
      when: ansible_facts['os_family'] == "RedHat" and install_type == "docker"

    - name: Create and start Jenkins Docker container
      docker_container:
        name: Jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
        volumes:
          - "{{ mount_path }}:/var/jenkins_home"
      when: install_type == "docker"

    - name: Install Jenkins on Debian/Ubuntu
      import_tasks: jenkins-playbooks/debian-ubuntu.yml
      when: ansible_facts['os_family'] == "Debian" and install_type != "docker"
    
    - name: Install Jenkins on Fedora
      import_tasks: jenkins-playbooks/fedora.yml
      when: ansible_facts['os_family'] == "Fedora" and install_type != "docker"
    
    - name: Install Jenkins on Red Hat/Alma/Rocky
      import_tasks: jenkins-playbooks/redhat.yml
      when: ansible_facts['os_family'] == "RedHat" and install_type != "docker"

    - name: Check Jenkins service status (non-Docker)
      systemd:
        name: jenkins
        state: started
      register: jenkins_service_status
      ignore_errors: yes
      when: install_type != "docker"

    - name: Get Jenkins initial admin password (non-Docker)
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_admin_password
      when: jenkins_service_status is defined and jenkins_service_status.changed and install_type != "docker"
    
    - name: Print Jenkins initial admin password (non-Docker)
      debug:
        msg: "Initial Admin Password: {{ jenkins_initial_admin_password.stdout }}"
      when: jenkins_initial_admin_password is defined and not jenkins_initial_admin_password.failed and install_type != "docker"

    - name: Get Jenkins initial admin password from Docker container
      command: docker exec Jenkins cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_admin_password
      when: install_type == "docker"
    
    - name: Print Jenkins initial admin password (Docker)
      debug:
        msg: "Initial Admin Password: {{ jenkins_initial_admin_password.stdout }}"
      when: jenkins_initial_admin_password is defined and not jenkins_initial_admin_password.failed and install_type == "docker"
