---
- name: Install Docker on Fedora
  hosts: all
  become: true
  tasks:
    - name: Remove older versions of Docker
      dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      ignore_errors: yes

    - name: Install required packages for Docker
      dnf:
        name:
          - dnf-plugins-core
        state: present

    - name: Add Docker's official repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install Docker Engine
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        allow_downgrade: yes
