---
- name: Install OpenJDK for Jenkins
  dnf:
    name: java-11-openjdk
    state: present

- name: Add Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Import Jenkins repository key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled on boot
  systemd:
    name: jenkins
    state: started
    enabled: yes
