---
- name: Install OpenJDK for Jenkins
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Jenkins repository key
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins is started and enabled on boot
  systemd:
    name: jenkins
    state: started
    enabled: yes
